### ISSUE TITLE
API Tracking issue: full links implementation

### ISSUE THREAD

**Issue by bibliotechie** [bibliotechie/antithesis#40]
Now that #30 is done, we need to actually add correct links for what the client is expecting (or modify the client to not expect it). This issue will track the progress on that, linking to the more specific issue or PR blocking the link's inclusion.

- [ ] "account.settings": #38
- [x]  "forgot-password": #39
- [ ]  "groups.new": TBD
- [x]  "help": #39
- [ ]  "oauth.authorize": TBD
- [ ]  "oauth.revoke": TBD
- [ ]  "search.tag": TBD
- [ ]  "signup": #37
- [ ]  "user": TBD
